defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: EP1000
subtitle: Digital Fab & Prototyping Fundamentals
baseurl: "/EP1000"  # the subpath of your site, e.g. /blog
# theme: panthera-jekyll
remote-theme: christianezeani/panthera-jekyll

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: About
    link: /about.html
    icon: ""

  - text: Fablab Safety
    link: /docs/safety.html
    icon: ""

  - text: Learning Prototyping
    link: /docs/prototype.html
    icon: ""

  - text: Web Development
    link: /docs/web.html
    icon: ""

  - text: Github & Version Control
    link: /docs/version.html
    icon: ""

  - text: Computer Graphics
    link: /docs/graphics.html
    icon: ""

  - text: Fusion 360
    link: /docs/fusion.html
    icon: ""

  - text: 3D Printing
    link: /docs/3dprint.html
    icon: ""

  - text: Laser Cutting
    link: /docs/laser.html
    icon: ""

  - text: Contact
    link: /contact.html
    icon: ""

  - text: Final Project
    link: /docs/project.html
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: ""
    icon: fab fa-linkedin

  - name: github
    link: ""
    icon: fab fa-github-square

  - name: facebook
    link: ""
    icon: fab fa-facebook-square

  - name: twitter
    link: ""
    icon: fab fa-twitter
